### ISSUE TITLE
Inserir a parte de Arquitetura de estrutura

### ISSUE THREAD

**Issue by lucasmco** [CadeiraCuidadora/relatorio#24]

**Comment by lucasmco** [comment]
https://docs.google.com/document/d/1Q__7vjsHdrsLUhdoqsNZ1Qjc0vhIazhjGCQeXR15oNg/edit

https://docs.google.com/drawings/d/1JSDtBRzGwpCXivuNPokl5v0sUTxNx7stziy_rgagDmY/edit

A parte de Arquitetura de estrutura fica situada no cap 7 , no sub capitulo 7.3

**Comment by wiltonsr** [comment]
Nesta seção indicada já está o texto da arquitetura do projeto eletromecânico (issue #19)
