### ISSUE TITLE
Ref quebradas

### ISSUE THREAD

**Issue by DylanGuedes** [CadeiraCuidadora/relatorio#41]
A master ta com referencias quebradas. Usando \cite ao inves de \ref consertou o problema.

**Comment by wiltonsr** [comment]
Onde por exemplo? E citação de bibtex tem q ser por \cite sempre.

**Comment by DylanGuedes** [comment]
Em vários lugares tá um (???) em uma referência. Exemplo: página 35, uma referencia a figura.

**Comment by wiltonsr** [comment]
roda bibtex tcc.aux e depois pdflatex tcc.tex duas vezes que resolve. Acho que é problema no makefile
